version: '3.8'

services:
  casse-briques:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: casse-briques-game
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    network_mode: host
    restart: on-failure
